using System;
using System.Runtime.CompilerServices;

public static class BuffList
{
    public static bool CheckType(this TYPE self, int type) => 
        (self == type);

    public static bool CheckUpdateHp(int type) => 
        (((TYPE.ADD_MAXHP.CheckType(type) || TYPE.SUB_MAXHP.CheckType(type)) || TYPE.UP_MAXHP.CheckType(type)) || TYPE.DOWN_MAXHP.CheckType(type));

    public enum TYPE
    {
        ADD_DAMAGE = 13,
        ADD_INDIVIDUALITY = 40,
        ADD_MAXHP = 0x51,
        ADD_SELFDAMAGE = 0x16,
        AVOID_INSTANTDEATH = 0x49,
        AVOID_STATE = 0x1f,
        AVOIDANCE = 0x18,
        BATTLESTART_FUNCTION = 0x53,
        BREAK_AVOIDANCE = 0x19,
        COMMANDATTACK_FUNCTION = 0x59,
        DAMAGE_FUNCTION = 0x56,
        DEAD_FUNCTION = 0x4e,
        DEADATTACK_FUNCTION = 90,
        DELAY_FUNCTION = 0x4c,
        DISABLE_GENDER = 0x24,
        DONOT_ACT = 0x20,
        DONOT_NOBLE = 0x22,
        DONOT_RECOVERY = 0x23,
        DONOT_SKILL = 0x21,
        DOWN_ATK = 10,
        DOWN_COMMANDALL = 60,
        DOWN_COMMANDATK = 0x42,
        DOWN_COMMANDNP = 0x44,
        DOWN_COMMANSTAR = 0x43,
        DOWN_CRITICALDAMAGE = 0x13,
        DOWN_CRITICALPOINT = 4,
        DOWN_CRITICALRATE = 0x47,
        DOWN_DAMAGE = 12,
        DOWN_DAMAGEDROPNP = 0x5e,
        DOWN_DEFENCE = 0x2b,
        DOWN_DROPNP = 0x3f,
        DOWN_GAIN_HP = 0x41,
        DOWN_GIVEGAIN_HP = 0x58,
        DOWN_GRANTSTATE = 0x1c,
        DOWN_MAXHP = 80,
        DOWN_NPDAMAGE = 0x10,
        DOWN_SELFDAMAGE = 0x15,
        DOWN_SPECIALDEFENCE = 0x5c,
        DOWN_STARWEIGHT = 0x3d,
        DOWN_TOLERANCE = 30,
        ENTRY_FUNCTION = 0x5f,
        GUTS = 0x25,
        INVINCIBLE = 0x1a,
        NONE = 0,
        PIERCE_INVINCIBLE = 0x48,
        REDUCE_HP = 8,
        REDUCE_NP = 0x3e,
        REGAIN_HP = 7,
        REGAIN_NP = 5,
        REGAIN_NP_USED_NOBLE = 0x4d,
        REGAIN_STAR = 6,
        SELFTURNEND_FUNCTION = 0x55,
        SUB_DAMAGE = 14,
        SUB_INDIVIDUALITY = 0x29,
        SUB_MAXHP = 0x52,
        SUB_SELFDAMAGE = 0x17,
        UP_ATK = 9,
        UP_CHAGETD = 0x60,
        UP_COMMANDALL = 0x34,
        UP_COMMANDATK = 1,
        UP_COMMANDNP = 0x33,
        UP_COMMANDSTAR = 50,
        UP_CRITICALDAMAGE = 0x12,
        UP_CRITICALPOINT = 3,
        UP_CRITICALRATE = 70,
        UP_DAMAGE = 11,
        UP_DAMAGEDROPNP = 0x5d,
        UP_DEFENCE = 0x2a,
        UP_DROPNP = 0x11,
        UP_GAIN_HP = 0x40,
        UP_GIVEGAIN_HP = 0x57,
        UP_GRANTSTATE = 0x1b,
        UP_HATE = 0x26,
        UP_MAXHP = 0x4f,
        UP_NONRESIST_INSTANTDEATH = 0x4b,
        UP_NPDAMAGE = 15,
        UP_RESIST_INSTANTDEATH = 0x4a,
        UP_SELFDAMAGE = 20,
        UP_SPECIALDEFENCE = 0x5b,
        UP_STARWEIGHT = 2,
        UP_TOLERANCE = 0x1d,
        WAVESTART_FUNCTION = 0x54
    }
}

