using System;
using System.Collections.Generic;

public class DataNameKind
{
    protected static Dictionary<Kind, string> nameList;

    static DataNameKind()
    {
        Dictionary<Kind, string> dictionary = new Dictionary<Kind, string> {
            { 
                Kind.NONE,
                null
            },
            { 
                Kind.BATTLE,
                "battle"
            },
            { 
                Kind.TREASUREDEVICE,
                "mstTreasureDevice"
            },
            { 
                Kind.SERVANT,
                "mstSvt"
            },
            { 
                Kind.SERVANT_LIMIT,
                "mstSvtLimit"
            },
            { 
                Kind.SERVANT_TREASUREDEVICE,
                "mstSvtTreasureDevice"
            },
            { 
                Kind.SERVANT_CLASS,
                "mstClass"
            },
            { 
                Kind.SERVANT_SCRIPT,
                "mstSvtScript"
            },
            { 
                Kind.SERVANT_CARD,
                "mstSvtCard"
            },
            { 
                Kind.SERVANT_SKILL,
                "mstSvtSkill"
            },
            { 
                Kind.USER_SERVANT,
                "userSvt"
            },
            { 
                Kind.STAGE,
                "mstStage"
            },
            { 
                Kind.SERVANT_GROUP,
                "mstSvtGroup"
            },
            { 
                Kind.SPOT,
                "mstSpot"
            },
            { 
                Kind.SPOT_ROAD,
                "mstSpotRoad"
            },
            { 
                Kind.MAP_GIMMICK,
                "mstMapGimmick"
            },
            { 
                Kind.GIFT,
                "mstGift"
            },
            { 
                Kind.SUB_EQUIP,
                "mstSubEquip"
            },
            { 
                Kind.USER,
                "user"
            },
            { 
                Kind.USER_GAME,
                "userGame"
            },
            { 
                Kind.USER_DECK,
                "userDeck"
            },
            { 
                Kind.USER_SERVANT_COLLECTION,
                "userSvtCollection"
            },
            { 
                Kind.FRIENDSHIP,
                "mstFriendship"
            },
            { 
                Kind.GACHA,
                "mstGacha"
            },
            { 
                Kind.GACHA_IMAGE,
                "mstGachaImage"
            },
            { 
                Kind.USER_GACHA,
                "userGacha"
            },
            { 
                Kind.USER_ITEM,
                "userItem"
            },
            { 
                Kind.ITEM,
                "mstItem"
            },
            { 
                Kind.GACHA_TICKET,
                "mstGachaTicket"
            },
            { 
                Kind.ACCESSORY,
                "mstAccessary"
            },
            { 
                Kind.USER_ACCESSORY,
                "userAccessary"
            },
            { 
                Kind.USER_SUB_EQUIP,
                "userSubEquip"
            },
            { 
                Kind.TBL_USER_GAME,
                "tblUserGame"
            },
            { 
                Kind.SHOP,
                "mstShop"
            },
            { 
                Kind.STONE_SHOP,
                "mstStoneShop"
            },
            { 
                Kind.BANK_SHOP,
                "mstBankShop"
            },
            { 
                Kind.SHOP_SCRIPT,
                "mstShopScript"
            },
            { 
                Kind.EQUIP,
                "mstEquip"
            },
            { 
                Kind.EQUIP_EXP,
                "mstEquipExp"
            },
            { 
                Kind.EQUIP_SKILL,
                "mstEquipSkill"
            },
            { 
                Kind.USER_EQUIP,
                "userEquip"
            },
            { 
                Kind.USER_FORMATION,
                "userFormation"
            },
            { 
                Kind.SKILL,
                "mstSkill"
            },
            { 
                Kind.SKILL_LEVEL,
                "mstSkillLv"
            },
            { 
                Kind.SKILL_DETAIL,
                "mstSkillDetail"
            },
            { 
                Kind.FUNCTION,
                "mstFunc"
            },
            { 
                Kind.BUFF,
                "mstBuff"
            },
            { 
                Kind.GACHA_RELEASE,
                "mstGachaRelease"
            },
            { 
                Kind.USER_QUEST,
                "userQuest"
            },
            { 
                Kind.USER_EXP,
                "mstUserExp"
            },
            { 
                Kind.NEWS,
                "mstNews"
            },
            { 
                Kind.TELOP,
                "mstTelop"
            },
            { 
                Kind.OTHER_USER_GAME,
                "otherUserGame"
            },
            { 
                Kind.TBL_FRIEND,
                "tblFriend"
            },
            { 
                Kind.USER_PRESENT_BOX,
                "userPresentBox"
            },
            { 
                Kind.EVENT,
                "mstEvent"
            },
            { 
                Kind.QUEST,
                "mstQuest"
            },
            { 
                Kind.QUEST_RELEASE,
                "mstQuestRelease"
            },
            { 
                Kind.QUEST_PHASE,
                "mstQuestPhase"
            },
            { 
                Kind.QUEST_GROUP,
                "mstQuestGroup"
            },
            { 
                Kind.AREA,
                "mstArea"
            },
            { 
                Kind.BGM,
                "mstBgm"
            },
            { 
                Kind.WAR,
                "mstWar"
            },
            { 
                Kind.EVENT_QUEST,
                "mstEventQuest"
            },
            { 
                Kind.EVENT_CAMPAIGN,
                "mstEventCampaign"
            },
            { 
                Kind.COMBINE_QP,
                "mstCombineQp"
            },
            { 
                Kind.COMBINE_MATERIAL,
                "mstCombineMaterial"
            },
            { 
                Kind.EVENT_COMBINE,
                "mstEventCombine"
            },
            { 
                Kind.SERVANT_EXP,
                "mstSvtExp"
            },
            { 
                Kind.COMBINE_SKILL,
                "mstCombineSkill"
            },
            { 
                Kind.COMBINE_TREASUREDEVICE,
                "mstCombineTd"
            },
            { 
                Kind.SERVANT_COMMENT,
                "mstSvtComment"
            },
            { 
                Kind.ILLUSTRATOR,
                "mstIllustrator"
            },
            { 
                Kind.CV,
                "mstCv"
            },
            { 
                Kind.TREASUREDEVICE_LEVEL,
                "mstTreasureDeviceLv"
            },
            { 
                Kind.TREASUREDEVICE_DETAIL,
                "mstTreasureDeviceDetail"
            },
            { 
                Kind.USER_FOLLOWER,
                "userFollower"
            },
            { 
                Kind.NPC_DECK,
                "npcDeck"
            },
            { 
                Kind.NPC_FOLLOWER,
                "npcFollower"
            },
            { 
                Kind.NPC_SERVANT,
                "npcSvt"
            },
            { 
                Kind.NPC_SERVANT_FOLLOWER,
                "npcSvtFollower"
            },
            { 
                Kind.USER_EVENT,
                "userEvent"
            },
            { 
                Kind.USER_PROFILE,
                "userProfile"
            },
            { 
                Kind.USER_SHOP,
                "userShop"
            },
            { 
                Kind.USER_CONTINUE,
                "userContinue"
            },
            { 
                Kind.CONSTANT,
                "mstConstant"
            },
            { 
                Kind.CONSTANT_STR,
                "mstConstantStr"
            },
            { 
                Kind.COMMAND_SPELL,
                "mstCommandSpell"
            },
            { 
                Kind.AI,
                "mstAi"
            },
            { 
                Kind.AI_ACT,
                "mstAiAct"
            },
            { 
                Kind.SERVANT_VOICE,
                "mstSvtVoice"
            },
            { 
                Kind.ATTRI_RELATION,
                "mstAttriRelation"
            },
            { 
                Kind.CLASS_RELATION,
                "mstClassRelation"
            },
            { 
                Kind.EFFECT,
                "mstEffect"
            },
            { 
                Kind.EQUIP_IMAGE,
                "mstEquipImage"
            },
            { 
                Kind.COMBINE_LIMIT,
                "mstCombineLimit"
            },
            { 
                Kind.CARD,
                "mstCard"
            },
            { 
                Kind.COMBINE_QP_SVT_EQUIP,
                "mstCombineQpSvtEquip"
            },
            { 
                Kind.SERVANT_LIMIT_ADD,
                "mstSvtLimitAdd"
            },
            { 
                Kind.SERVANT_RARITY,
                "mstSvtRarity"
            },
            { 
                Kind.SET_ITEM,
                "mstSetItem"
            },
            { 
                Kind.AP_RECOVER,
                "mstApRecover"
            },
            { 
                Kind.BANNER,
                "mstBanner"
            },
            { 
                Kind.SHOP_RELEASE,
                "mstShopRelease"
            },
            { 
                Kind.EVENT_REWARD,
                "mstEventReward"
            },
            { 
                Kind.EVENT_DETAIL,
                "mstEventDetail"
            },
            { 
                Kind.EVENT_SERVANT,
                "mstEventSvt"
            },
            { 
                Kind.BOX_GACHA,
                "mstBoxGacha"
            },
            { 
                Kind.BOX_GACHA_BASE,
                "mstBoxGachaBase"
            },
            { 
                Kind.BOX_GACHA_EXTRA,
                "mstBoxGachaExtra"
            },
            { 
                Kind.BOX_GACHA_TALK,
                "mstBoxGachaTalk"
            },
            { 
                Kind.USER_BOX_GACHA,
                "userBoxGacha"
            },
            { 
                Kind.BOX_GACHA_HISTORY,
                "boxGachaHistory"
            },
            { 
                Kind.BATTLE_BG,
                "mstBattleBg"
            },
            { 
                Kind.TIPS,
                "mstTips"
            },
            { 
                Kind.DROP,
                "mstDrop"
            },
            { 
                Kind.USER_LOGIN,
                "userLogin"
            },
            { 
                Kind.VOICE,
                "mstVoice"
            },
            { 
                Kind.EVENT_REWARD_EXTRA,
                "mstEventRewardExtra"
            },
            { 
                Kind.EVENT_MISSION,
                "mstEventMission"
            },
            { 
                Kind.EVENT_MISSION_CONDITION,
                "mstEventMissionCondition"
            },
            { 
                Kind.EVENT_MISSION_COND_DETAIL,
                "mstEventMissionConditionDetail"
            },
            { 
                Kind.EVENT_MISSION_ACTION,
                "mstEventMissionAction"
            },
            { 
                Kind.SERVANT_EXCEED,
                "mstSvtExceed"
            },
            { 
                Kind.EVENT_REWARD_SET,
                "mstEventRewardSet"
            },
            { 
                Kind.USER_EVENT_MISSION,
                "userEventMission"
            },
            { 
                Kind.USER_EVENT_MISSION_COND_DETAIL,
                "userEventMissionConditionDetail"
            },
            { 
                Kind.BOX_GACHA_BASE_DETAIL,
                "mstBoxGachaBaseDetail"
            },
            { 
                Kind.CLOSED_MESSAGE,
                "mstClosedMessage"
            },
            { 
                Kind.USER_SERVANT_LEADER,
                "userSvtLeader"
            },
            { 
                Kind.FUNCTION_GROUP,
                "mstFuncGroup"
            },
            { 
                Kind.EVENT_RAID,
                "mstEventRaid"
            },
            { 
                Kind.TOTAL_EVENT_RAID,
                "totalEventRaid"
            },
            { 
                Kind.USER_TERM,
                "mstUserTrem"
            },
            { 
                Kind.GAME_ILLUSTRATION,
                "mstGameIllustration"
            },
            { 
                Kind.EVENT_SUPER_BOSS,
                "mstEventSuperBoss"
            },
            { 
                Kind.USER_SUPER_BOSS,
                "userEventSuperBoss"
            }
        };
        nameList = dictionary;
    }

    public static string GetName(Kind kind) => 
        nameList[kind];

    public enum Kind
    {
        NONE,
        BATTLE,
        TREASUREDEVICE,
        SERVANT,
        SERVANT_LIMIT,
        SERVANT_TREASUREDEVICE,
        SERVANT_CLASS,
        SERVANT_SCRIPT,
        SERVANT_CARD,
        SERVANT_SKILL,
        USER_SERVANT,
        STAGE,
        SERVANT_GROUP,
        SPOT,
        SPOT_ROAD,
        MAP_GIMMICK,
        GIFT,
        SUB_EQUIP,
        USER,
        USER_GAME,
        USER_DECK,
        USER_SERVANT_COLLECTION,
        FRIENDSHIP,
        GACHA,
        GACHA_IMAGE,
        USER_GACHA,
        USER_ITEM,
        ITEM,
        GACHA_TICKET,
        ACCESSORY,
        USER_ACCESSORY,
        USER_SUB_EQUIP,
        TBL_USER_GAME,
        SHOP,
        STONE_SHOP,
        BANK_SHOP,
        SHOP_SCRIPT,
        EQUIP,
        EQUIP_EXP,
        EQUIP_SKILL,
        USER_EQUIP,
        USER_FORMATION,
        SKILL,
        SKILL_LEVEL,
        SKILL_DETAIL,
        FUNCTION,
        BUFF,
        GACHA_RELEASE,
        USER_QUEST,
        USER_EXP,
        NEWS,
        TELOP,
        OTHER_USER_GAME,
        TBL_FRIEND,
        USER_PRESENT_BOX,
        EVENT,
        QUEST,
        QUEST_RELEASE,
        QUEST_PHASE,
        QUEST_GROUP,
        AREA,
        BGM,
        WAR,
        EVENT_QUEST,
        EVENT_CAMPAIGN,
        COMBINE_QP,
        COMBINE_MATERIAL,
        EVENT_COMBINE,
        SERVANT_EXP,
        COMBINE_SKILL,
        COMBINE_TREASUREDEVICE,
        SERVANT_COMMENT,
        ILLUSTRATOR,
        CV,
        TREASUREDEVICE_LEVEL,
        TREASUREDEVICE_DETAIL,
        USER_FOLLOWER,
        NPC_FOLLOWER,
        NPC_SERVANT,
        NPC_SERVANT_FOLLOWER,
        NPC_DECK,
        DROP,
        USER_EVENT,
        USER_PROFILE,
        USER_SHOP,
        USER_CONTINUE,
        CONSTANT,
        CONSTANT_STR,
        COMMAND_SPELL,
        AI,
        AI_ACT,
        SERVANT_VOICE,
        ATTRI_RELATION,
        CLASS_RELATION,
        EFFECT,
        EQUIP_IMAGE,
        COMBINE_LIMIT,
        CARD,
        COMBINE_QP_SVT_EQUIP,
        SERVANT_LIMIT_ADD,
        SERVANT_RARITY,
        SET_ITEM,
        AP_RECOVER,
        BANNER,
        SHOP_RELEASE,
        EVENT_REWARD,
        EVENT_DETAIL,
        EVENT_SERVANT,
        BOX_GACHA,
        BOX_GACHA_BASE,
        BOX_GACHA_EXTRA,
        BOX_GACHA_TALK,
        USER_BOX_GACHA,
        BOX_GACHA_HISTORY,
        BATTLE_BG,
        TIPS,
        USER_LOGIN,
        VOICE,
        EVENT_REWARD_EXTRA,
        EVENT_MISSION,
        EVENT_MISSION_CONDITION,
        EVENT_MISSION_COND_DETAIL,
        EVENT_MISSION_ACTION,
        EVENT_REWARD_SET,
        USER_EVENT_MISSION,
        USER_EVENT_MISSION_COND_DETAIL,
        BOX_GACHA_BASE_DETAIL,
        CLOSED_MESSAGE,
        USER_SERVANT_LEADER,
        FUNCTION_GROUP,
        EVENT_RAID,
        TOTAL_EVENT_RAID,
        USER_TERM,
        GAME_ILLUSTRATION,
        SERVANT_EXCEED,
        EVENT_SUPER_BOSS,
        USER_SUPER_BOSS
    }
}

