using System;

public class ManagerConfig
{
    public static readonly long ACCOUNTING_INITIALIZE_TIMEOUT = 30L;
    public static readonly string AndroidPackageName = "jp.co.fatedomaindummy.FGO.Sample";
    public static readonly string AndroidProjectID = "1";
    public static readonly string AppBuildDate = "20151023_1";
    public static readonly string AppVer = "1.14.0";
    public static readonly string DebugDataServerAddress = "http://data.fatedomaindummy.com/Debug1";
    public static readonly string DebugGameServerAddress = "debug1.fatedomaindummy.net";
    public static readonly bool DebugNetworkSecurity;
    public static readonly string DebugWebServerAddress = "webview.fatedomaindummy.com";
    public static readonly string Dev1DataServerAddress = "http://data.fatedomaindummy.com/Dev1";
    public static readonly string Dev1GameServerAddress = "dev1.fatedomaindummy.net";
    public static readonly string Dev2DataServerAddress = "http://data.fatedomaindummy.com/Dev2";
    public static readonly string Dev2GameServerAddress = "dev2.fatedomaindummy.net";
    public static readonly string Dev3DataServerAddress = "http://data.fatedomaindummy.com/Dev3";
    public static readonly string Dev3GameServerAddress = "dev3.fatedomaindummy.net";
    public static readonly string Dev4DataServerAddress = "http://data.fatedomaindummy.com/Dev4";
    public static readonly string Dev4GameServerAddress = "dev4.fatedomaindummy.net";
    public static string DevelopCDNAddress = string.Empty;
    public static string DevelopDataServerAddress = string.Empty;
    public static string DevelopGameServerAddress = string.Empty;
    public static readonly string DevelopmentAuthCode = "aK8mTxBJCwZyxBjNJSKA5xCWL7zKtgZEQNiZmffXUbyQd5aLun";
    public static readonly bool DevelopNetworkSecurity;
    public static readonly string DevelopWebServerAddress = "webview.fatedomaindummy.com";
    public static readonly bool DevNetworkSecurity;
    public static readonly string DevWebServerAddress = "webview.fatedomaindummy.com";
    public static readonly string EventDevDataServerAddress = "http://data.fatedomaindummy.com/Event";
    public static readonly string EventDevGameServerAddress = "event.fatedomaindummy.net";
    public static readonly bool EventDevNetworkSecurity;
    public static readonly string EventDevWebServerAddress = "event.fatedomaindummy.net";
    public static readonly float GAME_DATA_TIMEOUT = 30f;
    public static readonly string GameCloneDataServerAddress = "http://data.fatedomaindummy.com/Clone";
    public static readonly string GameCloneGameServerAddress = "clone.fatedomaindummy.net";
    public static readonly bool GameCloneNetworkSecurity;
    public static readonly string GameCloneWebServerAddress = "webview.fatedomaindummy.com";
    public static readonly int HEIGHT = 0x240;
    public static readonly string iOSApplicationID = "1";
    public static readonly bool IsNetworkMock;
    public static readonly bool IsTrueTargetPlatform = true;
    public static readonly long LIMIT_FREE_SIZE = 0x3200000L;
    public static readonly string MasterDataCacheVer = "Fgo_20160303_1";
    public static readonly string PlatformName = "Android";
    public static readonly string Qa1DataServerAddress = "http://data.fatedomaindummy.com/QA1";
    public static readonly string Qa1GameServerAddress = "qa1.fatedomaindummy.net";
    public static readonly string Qa2DataServerAddress = "http://data.fatedomaindummy.com/QA2";
    public static readonly string Qa2GameServerAddress = "qa2.fatedomaindummy.net";
    public static readonly string Qa3DataServerAddress = "http://data.fatedomaindummy.com/QA3";
    public static readonly string Qa3GameServerAddress = "qa3.fatedomaindummy.net";
    public static readonly string Qa4DataServerAddress = "http://data.fatedomaindummy.com/QA4";
    public static readonly string Qa4GameServerAddress = "qa4.fatedomaindummy.net";
    public static readonly bool QaNetworkSecurity;
    public static readonly string QaWebServerAddress = "webview.fatedomaindummy.com";
    public static readonly string ReleaseCloneDataServerAddress = "http://data.fatedomaindummy.com/RC";
    public static readonly string ReleaseCloneGameServerAddress = "rclone.fatedomaindummy.net";
    public static readonly bool ReleaseCloneNetworkSecurity;
    public static readonly string ReleaseCloneWebServerAddress = "webview.fatedomaindummy.com";
    public static readonly string ReleaseDataServerAddress = "http://data.fatedomaindummy.jp/AssetStorages";
    public static readonly string ReleaseGameServerAddress = "game.fatedomaindummy.jp";
    public static readonly bool ReleaseNetworkSecurity = true;
    public static readonly string ReleaseWebServerAddress = "webview.fatedomaindummy.jp";
    public static readonly int RETRY_COUNT = 3;
    public static readonly string SaveDataVer = "Fgo_20150511_1";
    public static readonly string ScriptDataServerAddress = "file://C:/FGO/Temporary/AssetStorages";
    public static readonly string ScriptGameServerAddress = "file://C:/FGO/Temporary/AssetStorages/Mock";
    public static readonly long SERVER_TIME_OVER_LIMIT = 0xe10L;
    public static readonly string ServerDefaultType = "GAME_SERVER";
    public static readonly string StagingDataServerAddress = "http://data.fatedomaindummy.com/Staging";
    public static readonly string StagingGameServerAddress = "staging.fatedomaindummy.net";
    public static readonly bool StagingNetworkSecurity;
    public static readonly string StagingWebServerAddress = "webview.fatedomaindummy.com";
    public static readonly float TIMEOUT = 30f;
    public static readonly bool UseAppServer;
    public static readonly bool UseClientNetworkParameterCheck = true;
    public static readonly bool UseDebugCommand;
    public static readonly bool UseMock;
    public static readonly bool UseStandaloneAsset = true;
    public static readonly bool UseWebViewAuthoring;
    public static readonly int WIDTH = 0x400;
    public static readonly float WORK_TIME = 1f;
}

